"""Private MRD wire-protocol constants.
Constants for ISMRMRD message handling.

This module defines constants for Gadgetron and ISMRMRD message identifiers,
struct formats for binary data serialization, and logging severity levels.
"""

import struct

# Gadgetron message identifiers
GADGET_MESSAGE_INT_ID_MIN = 0  # CONTROL
GADGET_MESSAGE_FILENAME = 1
GADGET_MESSAGE_CONFIG = 2
GADGET_MESSAGE_HEADER = 3
GADGET_MESSAGE_CLOSE = 4
GADGET_MESSAGE_TEXT = 5
GADGET_MESSAGE_QUERY = 6
GADGET_MESSAGE_RESPONSE = 7
GADGET_MESSAGE_ERROR = 8
GADGET_MESSAGE_INT_ID_MAX = 999  # CONTROL
GADGET_MESSAGE_EXT_ID_MIN = 1000  # CONTROL
GADGET_MESSAGE_ACQUISITION = 1001  # DEPRECATED
GADGET_MESSAGE_NEW_MEASUREMENT = 1002  # DEPRECATED
GADGET_MESSAGE_END_OF_SCAN = 1003  # DEPRECATED
GADGET_MESSAGE_IMAGE_CPLX_FLOAT = 1004  # DEPRECATED
GADGET_MESSAGE_IMAGE_REAL_FLOAT = 1005  # DEPRECATED
GADGET_MESSAGE_IMAGE_REAL_USHORT = 1006  # DEPRECATED
GADGET_MESSAGE_EMPTY = 1007  # DEPRECATED
GADGET_MESSAGE_ISMRMRD_ACQUISITION = 1008
GADGET_MESSAGE_ISMRMRD_IMAGE_CPLX_FLOAT = 1009
GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_FLOAT = 1010
GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_USHORT = 1011
GADGET_MESSAGE_DICOM = 1012
GADGET_MESSAGE_CLOUD_JOB = 1013  # UNSUPPORTED
GADGET_MESSAGE_GADGETCLOUD_JOB = 1014  # UNSUPPORTED
GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_CPLX_FLOAT = 1015  # DEPRECATED
GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_FLOAT = 1016  # DEPRECATED
GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_USHORT = 1017  # DEPRECATED
GADGET_MESSAGE_DICOM_WITHNAME = 1018  # UNSUPPORTED
GADGET_MESSAGE_DEPENDENCY_QUERY = 1019  # UNSUPPORTED
GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_SHORT = 1020  # DEPRECATED
GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_SHORT = 1021  # DEPRECATED
GADGET_MESSAGE_ISMRMRD_IMAGE = 1022
GADGET_MESSAGE_RECON_DATA = 1023
GADGET_MESSAGE_IMAGE_ARRAY = 1024
GADGET_MESSAGE_ISMRMRD_WAVEFORM = 1026
GADGET_MESSAGE_PMC_PAYLOAD = 1027  # PMC correction feedback: PmcPayload struct
GADGET_MESSAGE_BUCKET = 1050
GADGET_MESSAGE_EXT_ID_MAX = 4096

# Struct formats
GadgetMessageLength = struct.Struct("<I")
SIZEOF_GADGET_MESSAGE_LENGTH = len(GadgetMessageLength.pack(0))

GadgetMessageIdentifier = struct.Struct("<H")
SIZEOF_GADGET_MESSAGE_IDENTIFIER = len(GadgetMessageIdentifier.pack(0))

GadgetMessageConfigurationFile = struct.Struct("<1024s")
SIZEOF_GADGET_MESSAGE_CONFIGURATION_FILE = len(GadgetMessageConfigurationFile.pack(b""))

GadgetMessageAttribLength = struct.Struct("<Q")
SIZEOF_GADGET_MESSAGE_ATTRIB_LENGTH = len(GadgetMessageAttribLength.pack(0))

bool = struct.Struct("<?")
uint32 = struct.Struct("<I")
uint64 = struct.Struct("<Q")
uint16 = struct.Struct("<H")

# Logging severity levels
GADGET_LOGGING_DEBUG = "DEBUG   "
GADGET_LOGGING_INFO = "INFO    "
GADGET_LOGGING_WARNING = "WARNING "
GADGET_LOGGING_ERROR = "ERROR   "
GADGET_LOGGING_CRITICAL = "CRITICAL"
