/*
 * test_rf_stats.c -- RF statistics tests.
 *
 * Tests:
 *   1. get_rf_stats returns error for sequences without RF.
 *   2. get_rf_array returns 0 pulses for sequences without RF.
 *   3. Periodic RF amplitude file (from generate_rf_test_cases.m) loads
 *      and has plausible RF stats.
 *
 * Requires: data/01_ok_trap_extended_trap.seq,
 *           data/01_rfamp_ok_mrfingerprinting.seq
 */
#include "test_helpers.h"

/* ------------------------------------------------------------------ */
/*  RF stats on a gradient-only file returns error (no RF present)    */
/* ------------------------------------------------------------------ */

MU_TEST(test_rf_stats_no_rf)
{
    pulseqlib_collection* coll = NULL;
    pulseqlib_diagnostic  diag = PULSEQLIB_DIAGNOSTIC_INIT;
    pulseqlib_rf_stats    stats = PULSEQLIB_RF_STATS_INIT;
    int rc;

    rc = load_seq(TEST_SEQ_OK, &coll, &diag, 0);
    mu_assert(PULSEQLIB_SUCCEEDED(rc), "load ok_trap");

    rc = pulseqlib_get_rf_stats(coll, &stats, 0, 0);
    mu_assert(PULSEQLIB_FAILED(rc),
              "rf_stats should fail for sequence without RF");

    pulseqlib_collection_free(coll);
}

/* ------------------------------------------------------------------ */
/*  RF array returns empty for gradient-only file                     */
/* ------------------------------------------------------------------ */

MU_TEST(test_rf_array_no_rf)
{
    pulseqlib_collection* coll = NULL;
    pulseqlib_diagnostic  diag = PULSEQLIB_DIAGNOSTIC_INIT;
    pulseqlib_rf_stats* pulses = NULL;
    int rc, npulses;

    rc = load_seq(TEST_SEQ_OK, &coll, &diag, 0);
    mu_assert(PULSEQLIB_SUCCEEDED(rc), "load ok_trap");

    npulses = pulseqlib_get_rf_array(
        coll, &pulses, 0, PULSEQLIB_TR_REGION_MAIN);
    mu_assert(npulses == 0,
              "rf_array should return 0 pulses for no-RF sequence");

    free(pulses);
    pulseqlib_collection_free(coll);
}

/* ------------------------------------------------------------------ */
/*  Periodic RF file: load and check RF stats                         */
/* ------------------------------------------------------------------ */

MU_TEST(test_rf_stats_periodic_rf)
{
    pulseqlib_collection* coll = NULL;
    pulseqlib_diagnostic  diag = PULSEQLIB_DIAGNOSTIC_INIT;
    pulseqlib_rf_stats    stats = PULSEQLIB_RF_STATS_INIT;
    int rc;

    rc = load_seq("data/01_rfamp_ok_mrfingerprinting.seq", &coll, &diag, 0);
    if (PULSEQLIB_FAILED(rc)) {
        /* File may be stale; skip until regenerated by workflow */
        return;
    }

    rc = pulseqlib_get_rf_stats(coll, &stats, 0, 0);
    mu_assert(PULSEQLIB_SUCCEEDED(rc), "get_rf_stats should succeed");
    mu_assert(stats.flip_angle_deg > 0.0f, "flip > 0");
    mu_assert(stats.duration_us > 0.0f, "duration > 0");
    mu_assert(stats.base_amplitude_hz > 0.0f, "base_amplitude > 0");
    mu_assert(stats.num_samples > 0, "num_samples > 0");

    pulseqlib_collection_free(coll);
}

MU_TEST(test_rf_array_periodic_rf)
{
    pulseqlib_collection* coll = NULL;
    pulseqlib_diagnostic  diag = PULSEQLIB_DIAGNOSTIC_INIT;
    pulseqlib_rf_stats* pulses = NULL;
    int rc, npulses;

    rc = load_seq("data/01_rfamp_ok_mrfingerprinting.seq", &coll, &diag, 0);
    if (PULSEQLIB_FAILED(rc)) {
        /* File may be stale; skip until regenerated by workflow */
        return;
    }

    npulses = pulseqlib_get_rf_array(
        coll, &pulses, 0, PULSEQLIB_TR_REGION_MAIN);
    mu_assert(npulses > 0, "periodic RF should have pulses in main region");
    mu_assert(pulses != NULL, "pulse array should be non-NULL");
    mu_assert(pulses[0].flip_angle_deg > 0.0f,
              "first pulse should have positive flip angle");

    free(pulses);
    pulseqlib_collection_free(coll);
}

/* ------------------------------------------------------------------ */
/*  Suite                                                             */
/* ------------------------------------------------------------------ */

MU_TEST_SUITE(test_rf_stats_suite)
{
    MU_RUN_TEST(test_rf_stats_no_rf);
    MU_RUN_TEST(test_rf_array_no_rf);
    MU_RUN_TEST(test_rf_stats_periodic_rf);
    MU_RUN_TEST(test_rf_array_periodic_rf);
}

int test_rf_stats_main(void)
{
    MU_RUN_SUITE(test_rf_stats_suite);
    MU_REPORT();
    return MU_EXIT_CODE;
}
