"""Test plugin backed by a pulserver SequencePlugin implementation."""

from __future__ import annotations

import os
from pathlib import Path

from pulserver import SequencePlugin

PHASE_ENCODE_STEPS = 128
MILLISECONDS_PER_SECOND = 1000.0
EXPECTED_VENV_NAME = "EnvPulserver"


class DemoSequencePlugin(SequencePlugin):
    def get_default_protocol(self, _system):
        return _default_protocol()

    def validate_protocol(self, _system, protocol):
        return _validate(protocol)

    def make_sequence(self, _system, protocol, output_path, *, offline=False):
        _make_sequence(protocol, output_path)


def _assert_envpulserver() -> None:
    virtual_env = os.environ.get("VIRTUAL_ENV", "")
    if not virtual_env:
        raise RuntimeError(
            "Expected VIRTUAL_ENV to be set to EnvPulserver, but it is empty"
        )
    venv_root = Path(virtual_env)
    if venv_root.name != EXPECTED_VENV_NAME or not (venv_root / "pyvenv.cfg").is_file():
        raise RuntimeError(f"Expected EnvPulserver virtual env, got: {virtual_env}")


def get_default_protocol(_system):
    _assert_envpulserver()
    return _default_protocol()


def validate_protocol(_system, protocol):
    _assert_envpulserver()
    return _validate(protocol)


def make_sequence(_system, protocol, output_path, *, offline=False):
    _assert_envpulserver()
    _make_sequence(protocol, output_path)


def _default_protocol():
    return {
        "TE": {
            "type": "float",
            "value": 5.0,
            "min": 1.0,
            "max": 100.0,
            "incr": 0.1,
            "unit": "ms",
            "validate": "none",
        },
        "TR": {
            "type": "float",
            "value": 15.0,
            "min": 2.0,
            "max": 2000.0,
            "incr": 0.1,
            "unit": "ms",
            "validate": "none",
        },
    }


def _validate(protocol):
    te = protocol["TE"]["value"]
    tr = protocol["TR"]["value"]
    valid = te < tr
    duration = tr * PHASE_ENCODE_STEPS / MILLISECONDS_PER_SECOND if valid else None
    info = f"TA = {duration:.2f} s" if valid else "TE must be < TR"
    return {"valid": valid, "duration": duration, "info": info}


def _make_sequence(protocol, output_path):
    tr = protocol["TR"]["value"]
    Path(output_path).write_text(
        f"# Generated by DemoSequencePlugin\nTR={tr}\n", encoding="utf-8"
    )
