"""Test plugin backed by a pulserver PulseqSequence implementation."""

from __future__ import annotations

import os
from pathlib import Path

from pulserver import (
    PulseqSequence,
    TypeinFloatParam,
    UIParam,
    dict_to_protocol,
    protocol_to_dict,
)

PHASE_ENCODE_STEPS = 128
EXPECTED_VENV_NAME = "EnvPulserver"


class DemoPulseqSequence(PulseqSequence):
    def get_default_protocol(self, _opts):
        return {
            UIParam.TE: TypeinFloatParam(value=5.0, min=1.0, max=100.0, incr=0.1, unit="ms"),
            UIParam.TR: TypeinFloatParam(value=15.0, min=2.0, max=2000.0, incr=0.1, unit="ms"),
        }

    def validate_protocol(self, _opts, protocol):
        te = protocol[UIParam.TE].value
        tr = protocol[UIParam.TR].value
        valid = te < tr
        duration = tr * PHASE_ENCODE_STEPS / 1000.0 if valid else None
        info = f"TA = {duration:.2f} s" if valid else "TE must be < TR"
        return {"valid": valid, "duration": duration, "info": info}

    def make_sequence(self, _opts, protocol, output_path):
        tr = protocol[UIParam.TR].value
        Path(output_path).write_text(f"# Generated by DemoPulseqSequence\nTR={tr}\n", encoding="utf-8")


_SEQUENCE = DemoPulseqSequence()


def _assert_envpulserver() -> None:
    virtual_env = os.environ.get("VIRTUAL_ENV", "")
    venv_root = Path(virtual_env)
    if venv_root.name != EXPECTED_VENV_NAME or not (venv_root / "pyvenv.cfg").is_file():
        raise RuntimeError(f"Expected EnvPulserver virtual env, got: {virtual_env}")


def get_default_protocol(opts):
    _assert_envpulserver()
    return protocol_to_dict(_SEQUENCE.get_default_protocol(opts))


def validate_protocol(opts, protocol):
    _assert_envpulserver()
    protocol_obj = dict_to_protocol(protocol)
    return _SEQUENCE.validate_protocol(opts, protocol_obj)


def make_sequence(opts, protocol, output_path):
    _assert_envpulserver()
    protocol_obj = dict_to_protocol(protocol)
    _SEQUENCE.make_sequence(opts, protocol_obj, output_path)
