name: CI-CD

on: 
  push:
  pull_request:

jobs:
  test-python:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run tests
        run: pytest --cov=python/pulserver --cov-report=xml tests/python
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token:  ${{ secrets.CODECOV_TOKEN }}
          slug: INFN-MRI/pulserver

  test-nim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nim
        run: |
          curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH

      - name: Run Nim tests
        run: bash tests/nim/run_tests.sh
